# Generated by Django 4.2 on 2024-05-23 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='loses_pong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='loses_tictactoe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='player',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='winrate_pong',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='winrate_tictactoe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wins_pong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wins_tictactoe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
